name: Build GKI Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu git

      - name: Download Kernel Source
        run: |
          git clone --depth=1 https://android.googlesource.com/kernel/common -b android12-5.10 kernel-source

      - name: Build Kernel
        run: |
          cd kernel-source
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- gki_defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
