
name: Build GKI Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Build Kernel
        run: |
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- gki_defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
